version: "3"
services:
  jenkins:
    image: "jenkinsci/blueocean"
    volumes:
      - "jenkins_home:/var/jenkins_home"
      - "/var/run/docker.sock:/var/run/docker.sock"
    networks:
      - ci-net
    user: root

  sonarqube:
    image: sonarqube
    networks:
      - ci-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonardb:5432/sonar
    volumes:
      - sonar_conf:/opt/sonarqube/conf
      - sonar_data:/opt/sonarqube/data
      - sonar_extensions:/opt/sonarqube/extensions
      - sonar_plugins:/opt/sonarqube/lib/bundled-plugins

  sonardb:
    image: postgres
    networks:
      - ci-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - sonarsql:/var/lib/postgresql
      - sonarsql_data:/var/lib/postgresql/data

  proxy:
    image: "nginx"
    volumes:
      - "certs:/certs"
      - "./nginx.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - ci-net
    ports:
      - "444:444"
      - "445:445"
      - "50000:50000"

networks:
  ci-net:

volumes:
  sonar_conf:
  sonar_data:
  sonar_extensions:
  sonar_plugins:
  sonarsql:
  sonarsql_data:
  jenkins_home:
  certs:
    external: true
